#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (c) 2026 Dong Yuan, Shih daneshih1125@gmail.com
# Licensed under the MIT License.

import json
from omci import omcisemantic


def generate_tooltip(cid, iid, attrs):
    if not attrs:
        return f"ME {cid} ({iid})"

    lines = []

    for k, v in attrs.items():
        val_str = str(v)
        if cid == 47 and k == "TP type" and isinstance(v, int):
            val_str = omcisemantic.get_attr_semantic(47, "TP type", v)
        elif cid == 171 and k == "Association type" and isinstance(v, int):
            val_str = omcisemantic.get_attr_semantic(171, "Association type", v)

        lines.append(f"{k}: {val_str}\n")
    return "".join(lines)


def get_vis_elements(topo_data):
    """
    Convert logical topology data into UI elements for vis.js visualization.

    This function adds visual metadata such as hierarchical levels, colors,
    and HTML-formatted labels to the nodes and edges.

    Args:
        topo_data (dict): The clean dictionary containing 'nodes' and 'edges'
                          generated by generate_topo_data().

    Returns:
        tuple: (nodes, edges) formatted for vis.js DataSet.
    """
    vis_nodes = []
    vis_edges = []

    # Level map for hierarchical layout (0: UNI/Bottom -> 6: T-CONT/Top)
    level_map = {
        11: 0,  # PPTP
        329: 0,  # VEIP
        134: 0,  # IP HOST
        171: 1,  # Extended VLAN
        84: 1,  # VLAN Filter
        47: 2,  # MAC Bridge Port
        45: 3,  # MAC Bridge Service Profile
        46: 3,  # MAC Bridge Config Data
        130: 3,  # 802.1p Mapper Service Profile
        266: 4,  # GEM IWTP
        281: 4,  # Multicast GEM IWTP
        268: 5,  # GEM Port CTP
        262: 6,  # T-CONT
    }

    # Process nodes
    for node in topo_data["nodes"]:
        cid = node["class_id"]
        iid = node["inst_id"]
        name = node["name"]
        attrs = node["attributes"]

        # Formatting label for human readability in HTML
        # Stripping suffixes for a cleaner look as per original design
        clean_name = (
            name.replace("_CONFIGURATION_DATA", "")
            .replace("_SERVICE_PROFILE", "")
            .replace("_DATA", "")
        )
        display_label = f"{clean_name} ({cid})\n({iid})"

        # Generate tooltip for hover interaction
        tooltip = generate_tooltip(cid, iid, attrs)

        # ONU-created MEs have square corners, OLT-created have rounded corners
        is_onu_created = cid in [11, 134, 329, 262]
        node_level = level_map.get(cid, 3)

        vis_nodes.append(
            {
                "id": node["id"],
                "label": display_label,
                "title": tooltip,
                "shape": "box",
                "margin": 10,
                "level": node_level,
                "shapeProperties": {"borderRadius": 0 if is_onu_created else 8},
                "color": {
                    "background": "#C2FABC" if is_onu_created else "#97C2FC",
                    "border": "#2B7CE9",
                },
                "font": {"multi": True, "size": 14},
                "group": str(cid),
            }
        )

    # Process edges
    for edge in topo_data["edges"]:
        # Convert AI-ready source/target back to vis.js from/to format
        vis_edge = {
            "from": edge["source"],
            "to": edge["target"],
            "label": edge.get("label", edge["relation"]),
            "arrows": "to",
        }

        # Apply specific visual styles based on relation/label
        # (e.g., VLAN Filter uses dashed lines)
        if edge.get("label") == "Filter-on":
            vis_edge["dashes"] = True

        vis_edges.append(vis_edge)

    return vis_nodes, vis_edges


def export_to_html(mib_db):
    nodes, edges = get_vis_elements(mib_db)
    template = """
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>OMCI Graph - MAC Bridged Topology</title>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vis-network/9.1.2/standalone/umd/vis-network.min.js"></script>
    <style type="text/css">
        body { font-family: "Microsoft JhengHei", Arial, sans-serif; margin: 0; padding: 20px; background-color: #f5f7fa; }
        #omci-network {
            width: 100%;
            height: calc(100vh - 120px);
            border: 1px solid #d3d3d3;
            background-color: #ffffff;
            border-radius: 8px;
        }
        .legend { margin-top: 15px; display: flex; gap: 20px; font-size: 14px; }
        .box-sample { width: 16px; height: 16px; display: inline-block; vertical-align: middle; border: 1px solid #666; }
    </style>
</head>
<body>
    <h2>OMCI Logical Topology</h2>
    <div class="legend">
        <div><span class="box-sample" style="border-radius: 0px; background: #C2FABC;"></span> <b>ONU Created:</b></div>
        <div><span class="box-sample" style="border-radius: 6px; background: #97C2FC;"></span> <b>OLT Created:</b></div>
    </div>
    <div id="omci-network"></div>

    <script type="text/javascript">
        var container = document.getElementById('omci-network');
        var nodes = new vis.DataSet(__NODES__);
        var edges = new vis.DataSet(__EDGES__);
        var data = { nodes: nodes, edges: edges };
        var options = {
            layout: {
                hierarchical: {
                    enabled: true,
                    direction: 'DU',
                    sortMethod: 'defined',
                    levelSeparation: 150,
                    nodeSpacing: 150,
                    treeSpacing: 200,
                    edgeMinimization: true,
                    parentCentralization: true
                }
            },
            physics: {
                enabled: false,
                solver: 'forceAtlas2Based',
                forceAtlas2Based: {
                    gravitationalConstant: -100,
                    centralGravity: 0.01,
                    springLength: 150,
                    avoidOverlap: 1
                },
                stabilization: { iterations: 150 }
            },
            nodes: {
                margin: 15,
                widthConstraint: { minimum: 300, maximum: 450 },
                font: {
                    size: 32,
                    multi: true,
                    face: 'monospace',
                    bold: { color: '#000', size: 34 }
                },
                shadow: { enabled: true, size: 10 }
            },
            edges: {
                width: 3,
                smooth: {
                    enabled: true,
                    type: 'cubicBezier',
                    forceDirection: 'vertical',
                    roundness: 0.5
                },
                arrows: { to: { enabled: true, scaleFactor: 1.5 } }
            },
            interaction: {
                hover: true,
                navigationButtons: true
            }
        };
        var network = new vis.Network(container, data, options);
        network.once("stabilizationIterationsDone", function() {
            network.moveTo({
                position: {x: 0, y: 0},
                scale: 1.2,
                animation: false
            });
        });
    </script>
</body>
</html>
"""
    return template.replace("__NODES__", json.dumps(nodes)).replace(
        "__EDGES__", json.dumps(edges)
    )


# vim: set ts=4 sw=4 et:
